In [ ]:
from statsmodels.stats.weightstats import ztest as ztest

# IQ level for 20 pateints
data = [88,92,94,94,96,97,97,97,99,99,105,109,109,109,110,112,112,113,114,115]
ztest(data,value=100)

(np.float64(1.5976240527147705), np.float64(0.1101266701438426))

In [ ]:
# t test
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [ ]:
import numpy as np
ages_mean=np.mean(ages)
ages_mean

np.float64(30.34375)

In [ ]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [ ]:
age_sample

array([55, 35, 27, 18, 18, 50, 18, 19, 55, 18])

In [ ]:
from scipy.stats import ttest_1samp

In [ ]:
ttest_1samp(age_sample,30)

TtestResult(statistic=np.float64(0.2536481420698098), pvalue=np.float64(0.8054668297730091), df=np.int64(9))

In [ ]:
ttest_1samp(age_sample,31)

TtestResult(statistic=np.float64(0.05853418663149468), pvalue=np.float64(0.9546021874862545), df=np.int64(9))

In [ ]:
# consider another example
#ages of the college students(population)
#1 class student mean of all the ages

In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(6)
school_ages=stats.poisson.rvs(loc=18,mu=35,size=1500)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)

In [ ]:
school_ages

array([62, 59, 44, ..., 45, 52, 50])

In [ ]:
classA_ages

array([52, 46, 40, 40, 47, 50, 51, 45, 44, 52, 46, 53, 43, 44, 51, 50, 54,
       42, 54, 45, 61, 53, 49, 46, 47, 41, 45, 51, 43, 45, 48, 50, 40, 52,
       44, 55, 54, 40, 45, 46, 54, 42, 46, 35, 51, 51, 46, 48, 47, 35, 52,
       52, 39, 44, 48, 40, 42, 46, 47, 45])

In [ ]:
classA_ages.mean()

np.float64(46.9)

In [ ]:
p_value=ttest_1samp(classA_ages,school_ages.mean())

In [ ]:
school_ages.mean()

np.float64(53.303333333333335)

In [ ]:
p_value_result=ttest_1samp(classA_ages,school_ages.mean())
p_value = p_value_result.pvalue
if p_value < 0.05:
  print("Reject HO")
else:
  print("Accept HO")

Reject HO
